# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import eventex.subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20160123_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='keyHash',
            field=models.CharField(default=eventex.subscriptions.models.hash_, max_length=40, verbose_name='hash'),
        ),
    ]
